import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";


export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main className="relative overflow-hidden bg-[#121212]">
          {children}
        </main>  
        <Footer/>
      </body>
    </html>
  );
}
